# Generated by Django 4.1.2 on 2022-11-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="answers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
