# Generated by Django 4.1.2 on 2022-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_room_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="rank",
            field=models.CharField(default="chat", max_length=8),
        ),
    ]
