# Generated by Django 4.1.2 on 2022-11-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="users_subscribed",
            field=models.ManyToManyField(
                related_name="subscribed_tags",
                through="user.SubscribeTag",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lendinfo",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lend_infos",
                to="book.book",
            ),
        ),
        migrations.AddField(
            model_name="lendinfo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lend_infos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lendinfo",
            name="watchers",
            field=models.ManyToManyField(
                related_name="watching_lends",
                through="user.WatchLend",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lendimage",
            name="lend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="book.lendinfo",
            ),
        ),
        migrations.AddField(
            model_name="borrowinfo",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrow_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="borrowinfo",
            name="lend_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="book.lendinfo",
            ),
        ),
        migrations.AddField(
            model_name="booktag",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booktag",
                to="book.book",
            ),
        ),
        migrations.AddField(
            model_name="booktag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booktag",
                to="book.tag",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                related_name="books", through="book.BookTag", to="book.tag"
            ),
        ),
    ]
