# Generated by Django 4.1.2 on 2022-10-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booktag",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booktag",
                to="book.book",
            ),
        ),
        migrations.AlterField(
            model_name="booktag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booktag",
                to="book.tag",
            ),
        ),
        migrations.AlterField(
            model_name="lendinfo",
            name="questions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
