# Generated by Django 4.1.2 on 2022-11-22 07:15

import book.models.book
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=book.models.book.book_image_upload_to
            ),
        ),
    ]
