# Generated by Django 4.1.2 on 2022-11-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_title_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="book",
            name="brief",
            field=models.CharField(blank=True, default="정보 없음", max_length=400),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
