# Generated by Django 4.1.2 on 2022-12-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_title_alter_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTagConcat",
            fields=[
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tagconcat",
                        serialize=False,
                        to="book.book",
                    ),
                ),
                ("tag_concat", models.TextField(default=" ")),
            ],
        ),
    ]
