# Generated by Django 4.1.2 on 2022-11-04 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0004_usertag_tag_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="users",
        ),
        migrations.AddField(
            model_name="tag",
            name="users_subscribed",
            field=models.ManyToManyField(
                related_name="subscribed_tags",
                through="book.UserTag",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
