# Generated by Django 4.1.2 on 2022-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_author_alter_book_brief_alter_book_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=800),
        ),
    ]
