# Generated by Django 4.1.2 on 2022-11-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_remove_tag_users_tag_users_subscribed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertag",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="usertag",
            name="user",
        ),
    ]
