# Generated by Django 4.1.2 on 2022-11-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_remove_book_image_bookimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookimage",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookimage",
                to="book.book",
            ),
        ),
    ]
