# Generated by Django 4.1.2 on 2022-11-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecommend",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recommend",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("list", models.JSONField(blank=True, default=list)),
                ("current_version", models.IntegerField(default=0)),
                ("target_version", models.IntegerField(default=0)),
                ("queued_version", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="WatchLend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watching_watch_lend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watching_lend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watches_watch_lend",
                        to="book.lendinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscribeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usertag",
                        to="book.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usertag",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
