# Generated by Django 4.1.2 on 2022-11-04 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0006_remove_usertag_tag_remove_usertag_user"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usertag",
                        to="book.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usertag",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
