# Generated by Django 4.1.2 on 2022-11-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0002_subscribetag"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecommend",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recommend",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("list", models.JSONField(blank=True, default=list)),
                ("is_outdated", models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
