# Generated by Django 4.1.2 on 2022-11-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_userrecommend"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecommend",
            name="is_queued",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userrecommend",
            name="is_outdated",
            field=models.BooleanField(default=False),
        ),
    ]
