# Generated by Django 4.1.2 on 2022-11-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userrecommend_is_queued_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrecommend",
            name="is_outdated",
        ),
        migrations.RemoveField(
            model_name="userrecommend",
            name="is_queued",
        ),
        migrations.AddField(
            model_name="userrecommend",
            name="current_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userrecommend",
            name="queued_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userrecommend",
            name="target_version",
            field=models.IntegerField(default=0),
        ),
    ]
